### ISSUE TITLE
Error in Installing

### ISSUE THREAD

**Issue by tanujdhiman** [facebookresearch/AugLy#70]
## 🐛 Bug

![augly](https://user-images.githubusercontent.com/56601466/124162104-c55edc80-dabb-11eb-9251-eedf6c03fabe.PNG)

## To Reproduce

1. Please do the `scipy --version from 1.6.2 to 1.5.4`

## Environment

 - AugLy Version (e.g., 0.1.2): 0.1.3
 - OS (e.g., Linux): Windows
 - How you installed AugLy (`pip install augly`, clone & `pip install -e AugLy`): `pip install wheel-name`
 - Python version: 3.7
 - Other relevant packages (Tensorflow, etc):

**Comment by jbitton** [comment]
Hi @tanujdhiman -- sorry to hear you're facing issues with downloading the package.

I tried to reproduce your issue on Python version 3.7.0 and tried to download scipy==1.6.2, but I was actually able to install the package:

```
(test_env) jbitton-mbp:~ jbitton$ conda create -n test_env python=3.7.0
(base) jbitton-mbp:~ jbitton$ conda activate test_env
(test_env) jbitton-mbp:~ jbitton$ pip3 install scipy==1.6.2
Collecting scipy==1.6.2
  Using cached scipy-1.6.2-cp37-cp37m-macosx_10_9_x86_64.whl (30.7 MB)
Collecting numpy<1.23.0,>=1.16.5
  Using cached numpy-1.21.0-cp37-cp37m-macosx_10_9_x86_64.whl (16.8 MB)
Installing collected packages: numpy, scipy
Successfully installed numpy-1.21.0 scipy-1.6.2
(test_env) jbitton-mbp:~ jbitton$ python
Python 3.7.0 (default, Jun 28 2018, 07:39:16) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Additionally, I tried to simply install AugLy on Python 3.7.0 by running `pip install augly` and that also worked as expected. Could you potentially try to run `pip install augly` instead of `pip install augly-0.1.3-py3-none-any.whl`? Perhaps that has caused some unintended consequences?

**Comment by tanujdhiman** [comment]
Thanks for replying @jbitton ! 
Okay I'll try and let you know!

**Comment by tanujdhiman** [comment]
Yes, Thanks it is working fine !!!
